wip: comment callable workflow until common is updated and pinned core version

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -47,102 +47,103 @@ jobs:
       upgrade-flavors: ${{ steps.test-flavor.outputs.upgrade-flavors }}
 
   deploy-test:
-    needs: flavor-test
-    permissions: write-all
-    uses: defenseunicorns/uds-common/.github/workflows/test-deploy.yaml@callable_workflow_fix  #@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
-    with:
-      upgrade-flavors: ${{ needs.flavor-test.outputs.upgrade-flavors }}
-      flavor: ${{ matrix.flavor }}
-      type: ${{ matrix.type }}
-      runs-on: ubuntu-latest
-      clean-runner: false
-      upload-reports: playwright
-      timeout: 25
-    secrets: inherit # Inherits all secrets from the parent workflow.
-    strategy:
-      fail-fast: true
-      matrix:
-        type: [install, upgrade]
-        flavor: [upstream, registry1, unicorn]
-
-
-    # name: ${{ matrix.type }} ${{ matrix.flavor }}
-    # runs-on: ubuntu-latest
-    # timeout-minutes: 25
+    # TODO: need to fix how actions work in uds-common before this can be used
+    # needs: flavor-test
+    # permissions: write-all
+    # uses: defenseunicorns/uds-common/.github/workflows/test-deploy.yaml@callable_workflow_fix  #@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
+    # with:
+    #   upgrade-flavors: ${{ needs.flavor-test.outputs.upgrade-flavors }}
+    #   flavor: ${{ matrix.flavor }}
+    #   type: ${{ matrix.type }}
+    #   runs-on: ubuntu-latest
+    #   clean-runner: false
+    #   upload-reports: playwright
+    #   timeout: 25
+    # secrets: inherit # Inherits all secrets from the parent workflow.
     # strategy:
-    #   fail-fast: false
+    #   fail-fast: true
     #   matrix:
-    #     flavor: [upstream, registry1, unicorn]
     #     type: [install, upgrade]
+    #     flavor: [upstream, registry1, unicorn]
 
-    # steps:
-    #   - name: Checkout repository
-    #     uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
 
-    #   - name: Environment setup
-    #     uses: defenseunicorns/uds-common/.github/actions/setup@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
-    #     with:
-    #       registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
-    #       registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
-    #       ghToken: ${{ secrets.GITHUB_TOKEN }}
-    #       chainguardIdentity: ${{ secrets.CHAINGUARD_IDENTITY }}
+    name: ${{ matrix.type }} ${{ matrix.flavor }}
+    runs-on: ubuntu-latest
+    timeout-minutes: 25
+    strategy:
+      fail-fast: false
+      matrix:
+        flavor: [upstream, registry1, unicorn]
+        type: [install, upgrade]
 
-    #   - name: Playwright setup
-    #     uses: defenseunicorns/uds-common/.github/actions/playwright@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
 
-    #   - name: Test
-    #     uses: defenseunicorns/uds-common/.github/actions/test-deploy@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
-    #     with:
-    #       upgrade-flavors: ${{ needs.flavor-test.outputs.upgrade-flavors }}
-    #       flavor: ${{ matrix.flavor }}
-    #       type: ${{ matrix.type }}
+      - name: Environment setup
+        uses: defenseunicorns/uds-common/.github/actions/setup@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
+        with:
+          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
+          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
+          ghToken: ${{ secrets.GITHUB_TOKEN }}
+          chainguardIdentity: ${{ secrets.CHAINGUARD_IDENTITY }}
 
-    #   - name: Save logs
-    #     if: always()
-    #     uses: defenseunicorns/uds-common/.github/actions/save-logs@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
-    #     with:
-    #       suffix: ${{ matrix.type }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
+      - name: Playwright setup
+        uses: defenseunicorns/uds-common/.github/actions/playwright@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
 
-    #   - name: Print cluster info
-    #     if: always()
-    #     shell: bash -e -o pipefail {0}
-    #     run: |
-    #       kubectl get nodes -o wide
+      - name: Test
+        uses: defenseunicorns/uds-common/.github/actions/test-deploy@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
+        with:
+          upgrade-flavors: ${{ needs.flavor-test.outputs.upgrade-flavors }}
+          flavor: ${{ matrix.flavor }}
+          type: ${{ matrix.type }}
 
-    #   - name: Print pod info
-    #     if: always()
-    #     shell: bash -e -o pipefail {0}
-    #     run: |
-    #       kubectl get pods -A -o wide
+      - name: Save logs
+        if: always()
+        uses: defenseunicorns/uds-common/.github/actions/save-logs@24c8a2a48eeb33773b76b3587c489cb17496c9e0 # v0.12.0
+        with:
+          suffix: ${{ matrix.type }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
 
-    #   - name: Print service info
-    #     if: always()
-    #     shell: bash -e -o pipefail {0}
-    #     run: |
-    #       kubectl get svc -A -o wide
+      - name: Print cluster info
+        if: always()
+        shell: bash -e -o pipefail {0}
+        run: |
+          kubectl get nodes -o wide
 
-    #   - name: Print events
-    #     if: always()
-    #     shell: bash -e -o pipefail {0}
-    #     run: |
-    #       kubectl get events -A -o wide
+      - name: Print pod info
+        if: always()
+        shell: bash -e -o pipefail {0}
+        run: |
+          kubectl get pods -A -o wide
 
-    #   - name: Print Jenkins pod logs
-    #     if: always()
-    #     shell: bash -e -o pipefail {0}
-    #     run: |
-    #       kubectl logs jenkins-0 -n jenkins
+      - name: Print service info
+        if: always()
+        shell: bash -e -o pipefail {0}
+        run: |
+          kubectl get svc -A -o wide
 
-    #   - name: Upload screenshot on failure
-    #     if: failure()
-    #     uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
-    #     with:
-    #       name: playwright-screenshot
-    #       path: tests/screenshots/*
+      - name: Print events
+        if: always()
+        shell: bash -e -o pipefail {0}
+        run: |
+          kubectl get events -A -o wide
 
-    #   - name: Upload video on failure
-    #     if: failure()
-    #     uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
-    #     with:
-    #       name: playwright-video
-    #       path: tests/.playwright/output/*
+      - name: Print Jenkins pod logs
+        if: always()
+        shell: bash -e -o pipefail {0}
+        run: |
+          kubectl logs jenkins-0 -n jenkins
+
+      - name: Upload screenshot on failure
+        if: failure()
+        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
+        with:
+          name: playwright-screenshot
+          path: tests/screenshots/*
+
+      - name: Upload video on failure
+        if: failure()
+        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
+        with:
+          name: playwright-video
+          path: tests/.playwright/output/*
